import { useState, useEffect, useRef, useCallback } from "react";
import "../styles/News.css";

const NEWS_ITEMS = [
  {
    id: 9,
    title: "Final Design Workflow Established",
    date: "March 20, 2026",
    category: "Milestone",
    video: "/news/video_2.mp4",
    description: "A complete design workflow was established, outlining the process from concept development to prototyping and manufacturing. This structured approach improved efficiency and coordination within the team, ensuring a smoother progression for future development stages.",
  },
  {
    id: 8,
    title: "Initial AI-Based 3D Visualization Attempts",
    date: "March 2, 2026",
    category: "Event",
    image: "/news/news_8.jpg",
    description: "The team explored early attempts at using AI tools to generate 3D visualizations of their design. While experimental, these efforts provided new perspectives on the system's structure and helped refine ideas for future modeling and presentation.",
  },
  {
    id: 7,
    title: "First System Layout Completed",
    date: "February 17, 2026",
    category: "Milestone",
    image: "/news/news_7.jpg",
    description: "An initial layout of the system was organized, defining the placement of components and wiring. This structured arrangement improved clarity in assembly and allowed the team to better understand spatial requirements and system integration.",
  },
  {
    id: 6,
    title: "Finalized Design and Aluminum Component Fabrication",
    date: "February 5, 2026",
    category: "Milestone",
    image: "/news/news_4.jpg",
    description: "The team finalized their design and transitioned into manufacturing a physical aluminum component. Using machine lab equipment, a precise and durable part was produced based on CAD models. This marked a significant move toward a more refined and production-ready prototype.",
  },
  {
    id: 5,
    title: "Output Voltage Measurement from Engine Tests",
    date: "January 17, 2026",
    category: "Event",
    image: "/news/news_6.jpg",
    description: "During engine testing, the team successfully measured the electrical output generated by the system. Recorded voltage data confirmed that the engines could produce usable energy, providing key validation for the project's intended functionality and efficiency.",
  },
  {
    id: 4,
    title: "Machining and Component Fabrication Advances",
    date: "December 15, 2025",
    category: "Event",
    image: "/news/news_1.jpg",
    description: "The team constructed and tested their first full prototype within an engineering laboratory. Compared to earlier versions, this prototype featured improved assembly and more stable components. Testing confirmed enhanced performance and reliability, representing a major step forward in the project.",
  },
  {
    id: 3,
    title: "First Prototype Created at Home",
    date: "December 6, 2025",
    category: "Milestone",
    image: "/news/news_5.jpg",
    description: "An initial prototype was assembled in a home environment using basic components and improvised setups. Despite its simplicity, the prototype successfully demonstrated the core concept, allowing the team to validate ideas before moving into more advanced development stages.",
  },
  {
    id: 2,
    title: "First Design Sketch Developed",
    date: "November 30, 2025",
    category: "Milestone",
    image: "/news/news_3.jpg",
    description: "The team produced their first conceptual design sketches, outlining the core structure and functionality of the system. These early drawings helped visualize the overall approach and served as a foundation for digital modeling and future prototype development.",
  },
  {
    id: 1,
    title: "First Engine Tests Completed",
    date: "November 23, 2025",
    category: "Milestone",
    video: "/news/video_1.mp4",
    description: "The engineering team conducted their first round of engine tests, marking a crucial early milestone in the project. Initial trials confirmed that the engines were operational, demonstrating visible motion and basic energy conversion. These tests provided essential performance data and highlighted areas for further refinement.",
  },
];

function isEmbedUrl(url) {
  return !!url && /youtu(\.be|be\.com)|vimeo\.com/.test(url);
}

function formatTime(s) {
  if (!s || isNaN(s)) return "0:00";
  return `${Math.floor(s / 60)}:${String(Math.floor(s % 60)).padStart(2, "0")}`;
}

function Lightbox({ item, onClose }) {
  const videoRef = useRef(null);
  const [playing, setPlaying]       = useState(false);
  const [progress, setProgress]     = useState(0);
  const [volume, setVolume]         = useState(1);
  const [duration, setDuration]     = useState(0);
  const [videoError, setVideoError] = useState(false);
  const [videoLoading, setVideoLoading] = useState(true);
  const [flashIcon, setFlashIcon]   = useState(null);

  useEffect(() => {
    const onKey = (e) => e.key === "Escape" && onClose();
    document.addEventListener("keydown", onKey);
    document.body.style.overflow = "hidden";
    document.documentElement.style.overflow = "hidden";
    document.documentElement.classList.add("nav-open");
    return () => {
      document.removeEventListener("keydown", onKey);
      document.body.style.overflow = "";
      document.documentElement.style.overflow = "";
      document.documentElement.classList.remove("nav-open");
    };
  }, [onClose]);

  const syncTime = useCallback(() => {
    const v = videoRef.current;
    if (v) { setProgress(v.currentTime); setDuration(v.duration || 0); }
  }, []);

  const togglePlay = useCallback(() => {
    const v = videoRef.current;
    if (!v) return;
    if (v.paused) {
      v.play().then(() => { setPlaying(true); setFlashIcon("▶"); }).catch(() => {});
    } else {
      v.pause();
      setPlaying(false);
      setFlashIcon("⏸");
    }
    setTimeout(() => setFlashIcon(null), 600);
  }, []);

  const onSeek = (e) => {
    const v = videoRef.current;
    if (!v || !duration) return;
    v.currentTime = (e.target.value / 100) * duration;
    setProgress(v.currentTime);
  };

  const onVolume = (e) => {
    const val = parseFloat(e.target.value);
    if (videoRef.current) {
      videoRef.current.volume = val;
      videoRef.current.muted = val === 0;
    }
    setVolume(val);
  };

  const hasVideo = !!item.video;
  const hasImage = !!item.image;
  const isEmbed  = hasVideo && isEmbedUrl(item.video);
  const isNative = hasVideo && !isEmbed;

  return (
    <div
      className="lb-overlay"
      onClick={(e) => e.target === e.currentTarget && onClose()}
      role="dialog"
      aria-modal="true"
      aria-label={`Media viewer: ${item.title}`}
    >
      <div className="lb-panel">
        <button className="lb-close" onClick={onClose} aria-label="Close">✕</button>

        <div className="lb-media">
          {isNative && (
            <>
              {videoLoading && !videoError && (
                <div className="lb-video-loading">
                  <div className="lb-spinner" />
                  <span>Loading video…</span>
                </div>
              )}

              {videoError ? (
                <div className="lb-video-error">
                  <span className="lb-video-error-icon">⚠️</span>
                  <p>Could not load video.</p>
                  <p className="lb-video-error-sub">
                    Make sure the file exists at: <code>{item.video}</code>
                  </p>
                </div>
              ) : (
                <div className="lb-video-wrapper" onClick={togglePlay}>
                  <video
                    ref={videoRef}
                    className="lb-video"
                    src={item.video}
                    preload="auto"
                    playsInline
                    onLoadedMetadata={(e) => {
                      syncTime();
                      setVideoLoading(false);
                      e.target.play().then(() => setPlaying(true)).catch(() => {});
                    }}
                    onCanPlay={() => setVideoLoading(false)}
                    onTimeUpdate={syncTime}
                    onEnded={() => setPlaying(false)}
                    onError={() => { setVideoError(true); setVideoLoading(false); }}
                  />
                  {flashIcon && <div className="lb-flash-icon">{flashIcon}</div>}
                </div>
              )}

              {!videoLoading && !videoError && (
                <div className="lb-controls" onClick={(e) => e.stopPropagation()}>
                  <button className="lb-ctrl-btn lb-play-btn" onClick={togglePlay} aria-label={playing ? "Pause" : "Play"}>
                    {playing ? "⏸" : "▶"}
                  </button>
                  <span className="lb-time">{formatTime(progress)}</span>
                  <input
                    type="range" className="lb-seek"
                    min={0} max={100} step={0.1}
                    value={duration ? (progress / duration) * 100 : 0}
                    onChange={onSeek}
                    aria-label="Seek"
                  />
                  <span className="lb-time">{formatTime(duration)}</span>
                  <span className="lb-vol-icon">🔊</span>
                  <input
                    type="range" className="lb-volume"
                    min={0} max={1} step={0.01}
                    value={volume}
                    onChange={onVolume}
                    onInput={onVolume}
                    aria-label="Volume"
                  />
                </div>
              )}
            </>
          )}

          {isEmbed && (
            <iframe
              className="lb-iframe"
              src={item.video}
              title={item.title}
              allow="autoplay; fullscreen; picture-in-picture"
              allowFullScreen
            />
          )}

          {!hasVideo && hasImage && (
            <img className="lb-img" src={item.image} alt={item.title} />
          )}
        </div>

        <div className="lb-caption">
          <span className="lb-caption-category">{item.category}</span>
          <span className="lb-caption-title">{item.title}</span>
          <span className="lb-caption-date">{item.date}</span>
        </div>
      </div>
    </div>
  );
}

function NewsCard({ item, onOpenLightbox }) {
  const hasVideo = !!item.video;
  const hasImage = !!item.image;
  const hasMedia = hasVideo || hasImage;

  const renderThumbnail = () => {
    if (hasVideo && !isEmbedUrl(item.video)) {
      return (
        <div className="news-card-video-thumb">
          <video
            className="news-card-video-preview"
            src={`${item.video}#t=0.001`}
            preload="metadata"
            muted
            playsInline
          />
          <div className="news-card-play-btn" aria-hidden="true">▶</div>
        </div>
      );
    }
    if (hasVideo && isEmbedUrl(item.video)) {
      return hasImage ? (
        <>
          <img src={item.image} alt={item.title} />
          <div className="news-card-play-btn" aria-hidden="true">▶</div>
        </>
      ) : (
        <div className="news-card-image-placeholder">
          <span className="news-card-image-icon">🎬</span>
          <span className="news-card-image-hint">Click to watch video</span>
        </div>
      );
    }
    if (hasImage) return <img src={item.image} alt={item.title} />;
    return (
      <div className="news-card-image-placeholder">
        <span className="news-card-image-icon">📰</span>
        <span className="news-card-image-hint">Add image path to NEWS_ITEMS in News.jsx</span>
      </div>
    );
  };

  return (
    <article className="news-card">
      <div
        className={`news-card-image${hasMedia ? " news-card-image--clickable" : ""}`}
        onClick={hasMedia ? () => onOpenLightbox(item) : undefined}
        role={hasMedia ? "button" : undefined}
        tabIndex={hasMedia ? 0 : undefined}
        aria-label={hasMedia ? `Open fullscreen: ${item.title}` : undefined}
        onKeyDown={hasMedia ? (e) => e.key === "Enter" && onOpenLightbox(item) : undefined}
      >
        {renderThumbnail()}
        <span className="news-card-category">{item.category}</span>
        {hasMedia && (
          <span className="news-card-expand-hint" aria-hidden="true">
            {hasVideo ? "🎬 Click to watch" : "🔍 Click to expand"}
          </span>
        )}
      </div>

      <div className="news-card-body">
        <div className="news-card-date">
          <span className="news-date-icon">📅</span>
          {item.date}
        </div>
        <h2 className="news-card-title">{item.title}</h2>
        <p className="news-card-description">{item.description}</p>
      </div>
    </article>
  );
}

export default function News() {
  const [lightboxItem, setLightboxItem] = useState(null);

  return (
    <div id="news" className="page active">
      {lightboxItem && (
        <Lightbox item={lightboxItem} onClose={() => setLightboxItem(null)} />
      )}

      <section className="hero">
        <h1>News</h1>
        <p>Latest updates, milestones, and events from the Helios Project</p>
      </section>

      <div className="news-container">
        <div className="news-header-bar">
          <h2 className="news-section-title">
            <span>📡</span> Latest Articles
          </h2>
          <span className="news-count">
            {NEWS_ITEMS.length} article{NEWS_ITEMS.length !== 1 ? "s" : ""}
          </span>
        </div>

        {NEWS_ITEMS.length > 0 ? (
          <div className="news-list">
            {NEWS_ITEMS.map((item) => (
              <NewsCard key={item.id} item={item} onOpenLightbox={setLightboxItem} />
            ))}
          </div>
        ) : (
          <div className="news-empty">
            <span>📭</span>
            <p>No articles yet — check back soon.</p>
          </div>
        )}
      </div>
    </div>
  );
}
